// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1K-0ioKu6u0NKKD-71Ult7-lYWj1J1f0',
    appId: '1:161758734385:web:527f47340f0aa77c284d10',
    messagingSenderId: '161758734385',
    projectId: 'leafcare-4312f',
    authDomain: 'leafcare-4312f.firebaseapp.com',
    storageBucket: 'leafcare-4312f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuRGNhjoPp77teI3AikPURhgUoE6Fpho',
    appId: '1:161758734385:android:bbe58230316b112f284d10',
    messagingSenderId: '161758734385',
    projectId: 'leafcare-4312f',
    storageBucket: 'leafcare-4312f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraIUoO_sBZeKLp_7yIvbzjoVtr-E-WO4',
    appId: '1:161758734385:ios:8af552162174dabf284d10',
    messagingSenderId: '161758734385',
    projectId: 'leafcare-4312f',
    storageBucket: 'leafcare-4312f.firebasestorage.app',
    iosBundleId: 'com.example.leafcare',
  );

}